#!/usr/bin/env bash

set -e

RUSTFLAGS='-C link-arg=-s' cargo build --workspace --target wasm32-unknown-unknown --release
# cp target/wasm32-unknown-unknown/release/index.wasm ./res/
if test ! -d "./res"; then
    mkdir ./res
fi
ls target/wasm32-unknown-unknown/release/ | grep '.wasm' | while read -r line ; do
    cp -r target/wasm32-unknown-unknown/release/$line res/$line
done